import {mkdirSync,writeFileSync,existsSync} from 'node:fs';
import {join} from 'node:path';
import {checkContent,root} from './check-content.js';
import type {ResearchMission} from '../../src/content/research-schema.js';
const c=checkContent();
const sourceMap=new Map(c.sources.map(s=>[s.id,s]));
const write=(path:string,text:string)=>{const file=join(root,path);mkdirSync(join(file,'..'),{recursive:true});writeFileSync(file,text);};
const escape=(text:string)=>text.replaceAll('|','\\|').replaceAll('\n',' ');
const refs=(m:{sourceNotes:{sourceId:string}[]})=>[...new Set(m.sourceNotes.map(s=>s.sourceId))].map(id=>{const s=sourceMap.get(id)!;return s.url?`[${id}](${s.url})`:id;}).join(', ');
write('game-docs/research/00-source-index.md',`# Source index\n\nSource-specific access dates are recorded in sources.json. Primary evidence outranks recollection. Mirrors and press-release republications share a source family; count families, not URLs, when assessing independence. A source supports only the claim/section named in a record. English names are working localizations.\n\n| ID | Source | Type / family | Access | Proves | Limits |\n| --- | --- | --- | --- | --- | --- |\n${c.sources.map(s=>`| ${s.id} | ${s.url?`[${escape(s.title)}](${s.url})`:escape(s.title)} | ${s.type} / ${s.family} | ${s.accessStatus} | ${escape(s.proves)} | ${escape(s.limitations)} |`).join('\n')}\n\nDiscovery inspected six Wonavy category pages and the Have Alice Free Mission category, then followed article links sequentially with cached, one-second-spaced HTML requests. No media was downloaded. Missing Romi subpages returned 404 and are recorded as unavailable. discovery.json stores headings and image-reference counts, not a transcript of each article.\n`);
const table=(items:ResearchMission[])=>`| Episode / ID | Korean title | English working title | Detailed walkthrough found? | Screenshots found? | Quest steps reconstructed? | Confidence | Sources | Implementation status |\n| --- | --- | --- | --- | --- | --- | --- | --- | --- |\n${items.map(m=>`| ${m.episodeNumber??m.id} | ${escape(m.name.koOriginal??'UNKNOWN')} | ${escape(m.name.en)} | ${m.walkthroughFound?'Yes: narrative; exact trigger/numeric extraction pending':'Not located'} | ${m.screenshotsFound} | ${m.questStepsReconstructed?'Yes':'No'} | ${m.confidence} (identity only) | ${refs(m)} | ${m.implementationStatus} |`).join('\n')}\n`;
write('game-docs/research/03-main-missions.md',`# Main mission coverage\n\nAll 103 numbers (0–102) are accounted for. Wonavy headings were compared against the readonly catalog for every number. The catalogs may share historical source wording. ${c.main.filter(m=>m.titleAgreement==='VARIANT').length} entries have differences beyond whitespace; all forms remain in JSON. ${c.main.filter(m=>m.milestones.scripted).length} have executable restoration scripts and ${c.main.filter(m=>m.milestones.playable).length} are playable in the local workbench; public gameplay remains disabled. None is fully historically verified. Illustrated articles are not automatically classified as screenshots.\n\n${table(c.main)}\n## Title variants\n\n${c.main.filter(m=>m.titleAgreement==='VARIANT').map(m=>`- Episode ${m.episodeNumber}: ${m.titleVariants.map(v=>`${v.sourceId}: ${v.text}`).join(' / ')}`).join('\n')}\n\nSee [implementation sequence](../architecture/arpia-implementation-sequence.md) and individual dossiers under missions/main.\n`);
write('game-docs/research/04-free-missions.md',`# Free Mission coverage\n\n37 named missions from the supplied list match the surviving wiki catalog. List order is not a historical mission number. The contemporary Have Alice category has 16 posts covering 15 entries here, including a two-post Ryoma walkthrough. This is a minimum catalog, not an exhaustive release list.\n\n${table(c.free)}\n## Additional leads\n\nA contemporary fishing-mission mention and Saturday event appear in [Have Alice /95](https://alicer.tistory.com/95). Exact title and mission ID are unknown; do not invent a numbered catalog entry. Seasonal/event content, teacher repeatables, promotion requirements and cooldowns remain open. Trial of Earth Spirit King and Angry Earth Spirit stay separate until the overlapping reward accounts are reconciled.\n`);
for(const m of [...c.main,...c.free]){
  const path=`game-docs/research/missions/${m.kind==='mainMission'?'main':'free'}/${m.id.split('.')[1]}.md`;
  // Preserve manually expanded dossiers on future report regeneration.
  if(existsSync(join(root,path)))continue;
  write(path,`# ${m.episodeNumber===null?m.id:`Episode ${m.episodeNumber}`} — ${m.name.en}\n\nKorean working title: ${m.name.koOriginal}\n\nHistorical release: ${m.id==='main.102'?'Official 2012 landing-page listing survives; exact first release date unknown.':'Catalog/walkthrough attestation; exact first release date UNKNOWN.'}\n\nImplementation: **${m.implementationStatus}**. Historical identity: ${m.provenance} / ${m.confidence}. This is a research dossier, not an executable placeholder quest.\n\n## Sources\n\n${refs(m)}\n\n${m.sourceNotes.map(n=>`- ${n.sourceId}, ${n.section}: ${n.proves}`).join('\n')}\n\n## Observed title variants\n\n${m.titleVariants.map(v=>`- ${v.sourceId}: ${v.text}`).join('\n')}\n\n## Scoped findings\n\n${m.claims.length?m.claims.map(cl=>`- ${cl.field}: ${JSON.stringify(cl.value)} — ${cl.provenance}/${cl.confidence}; ${refs(cl)}`).join('\n'):'No objective-level claims extracted in this pass. Read the linked narrative before scripting.'}\n\n## Reconstruction fields\n\n| Field | Current evidence |\n| --- | --- |\n| Official description / story summary | See cited narrative; no original dialogue copied. |\n| Starting NPC / map | Only known if listed in scoped findings above. |\n| Prerequisites / required level / rank | UNKNOWN |\n| Required pets / magic / items | UNKNOWN except scoped findings |\n| Ordered objective flow and dialogue intent | NOT RECONSTRUCTED |\n| Exact travel route / triggers / flags | UNKNOWN |\n| Combat groups / bosses / quantities | UNKNOWN except scoped findings |\n| Puzzles / typed text / maze topology | UNKNOWN except scoped findings; no graph inferred |\n| Temporary companions / cutscenes | UNKNOWN except scoped findings |\n| EXP / Pin / Virtue rewards | UNKNOWN (null, not zero) |\n| Items / pets / spell / equipment rewards | UNKNOWN except scoped findings |\n| Unlocks / consequences / failure / repeatability | UNKNOWN |\n| Visual references | ${m.screenshotsFound} |\n| Video / timestamp | Not individually located |\n\n## Missing information\n\n${m.unknowns.map(x=>`- ${x}`).join('\n')}\n\n## Implementation gate\n\nReconstruct ordered steps, map/NPC placements, dependencies, branches and reward evidence before enabling play. Label authored English dialogue and estimated rules individually. Keep CATALOGED, RESEARCHED, SCRIPTED, PLAYABLE and VERIFIED separate.\n`);
}
const report={date:'2026-09-09',main:{cataloged:c.main.length,narrativeFound:c.main.filter(m=>m.walkthroughFound).length,titleVariants:c.main.filter(m=>m.titleAgreement==='VARIANT').length,researched:c.main.filter(m=>m.milestones.researched).length,scripted:c.main.filter(m=>m.milestones.scripted).length,playable:c.main.filter(m=>m.milestones.playable).length,verified:c.main.filter(m=>m.milestones.verified).length},free:{cataloged:c.free.length,narrativeFound:c.free.filter(m=>m.walkthroughFound).length,exhaustive:false},entities:Object.fromEntries(['npc','map','pet','spell','monster','item'].map(kind=>[kind,c.records.filter(r=>r.kind===kind).length])),sources:{total:c.sources.length,unavailable:c.sources.filter(s=>s.accessStatus==='UNAVAILABLE').length},assets:{requiredIds:new Set(c.records.flatMap(r=>r.assetIds)).size,approved:c.approvedAssets},runtime:{quests:c.runtimeQuestCount,maps:c.runtimeMapCount},unresolvedFields:c.records.reduce((n,r)=>n+r.unknowns.length,0)};
write('research/research-report.json',JSON.stringify(report,null,2)+'\n');
write('research/research-report.md',`# Arpia research coverage\n\nGenerated from validated content, ${report.date}.\n\n- Main missions: **103/103 cataloged**, ${report.main.narrativeFound} narrative sources matched, ${report.main.titleVariants} title variants.\n- Narrative flow researched: ${report.main.researched}; scripted: ${report.main.scripted}; playable: ${report.main.playable}; historically verified: ${report.main.verified}.\n- Free Missions: **37 cataloged**, ${report.free.narrativeFound} with contemporary narrative posts. Exhaustiveness is unknown.\n- Entity counts: ${Object.entries(report.entities).map(([k,v])=>`${k}: ${v}`).join(', ')}.\n- Sources: ${report.sources.total} records; ${report.sources.unavailable} unavailable.\n- Assets: ${report.assets.requiredIds} requested logical IDs; **${report.assets.approved} approved**.\n- Executable quests/maps: ${report.runtime.quests}/${report.runtime.maps}. Runtime geometry is explicitly RESTORATION; no exact historical map topology is claimed.\n\n[Source index](../game-docs/research/00-source-index.md) · [Main missions](../game-docs/research/03-main-missions.md) · [Free Missions](../game-docs/research/04-free-missions.md) · [Contradictions](../game-docs/research/22-content-uncertainties.md) · [Implementation sequence](../game-docs/architecture/arpia-implementation-sequence.md)\n\nRun \`npm run research:check\` and \`npm run research:report\` from game-app.\n`);
console.log(JSON.stringify(report,null,2));
